platform :ios, '9.0'

target 'eye-detector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eye-detector
  pod 'TensorFlowLiteSwift'

  target 'eye-detectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eye-detectorUITests' do
    # Pods for testing
  end

end
